### ISSUE TITLE
[Bug]: Failed to load plugin schemas in Linux ARM64 builds

### ISSUE THREAD

**Issue by displague** [equinix/terraform-provider-equinix#434]
### Terraform Version

Terraform 1.6.2 and 1.5.7 on arm_linux

### Equinix Provider Version

1.18.1

### Terraform Config Files

```hcl
terraform {
  required_providers {
    equinix = {
      source = "equinix/equinix"
    }
  }
}

provider "equinix" {
  # set METAL_AUTH_TOKEN
}

resource "equinix_metal_device" "foo" {
  hostname         = "test"
  count            = 1
  plan             = "c3.medium.x86"
  metro            = "sv"
  operating_system = "custom_ipxe"
  billing_cycle    = "hourly"
  tags             = []
  project_id       = "!234"
  ipxe_script_url  = "https://example.com/foo"

  ip_address {
    type = "public_ipv4"
    cidr = 31
  }
  ip_address {
    type = "private_ipv4"
    cidr = 31
  }
  ip_address {
    type = "public_ipv6"
    cidr = 127
  }
}

resource "equinix_metal_device_network_type" "foo" {
  count     = 1
  device_id = equinix_metal_device.foo[count.index].id
  type      = "layer3"
}

### Debug Output

_No response_

### Panic Output

```sh
mjohansson@dev-qemu:~/dev/tf-test$ terraform  apply
╷
│ Error: Failed to load plugin schemas
│ 
│ Error while loading schemas for plugin components: Failed to obtain provider schema: Could not load the schema for provider registry.terraform.io/equinix/equinix: failed to instantiate provider
│ "registry.terraform.io/equinix/equinix" to obtain schema: Unrecognized remote plugin message: 
│ 
│ This usually means that the plugin is either invalid or simply
│ needs to be recompiled to support the latest protocol...
╵

Stack trace from the terraform-provider-equinix_v1.18.1 plugin:

fatal error: unknown caller pc

runtime stack:
runtime.throw({0xcd2a7c?, 0x1546880?})
        runtime/panic.go:1047 +0x40 fp=0xfffff9bd80b0 sp=0xfffff9bd8080 pc=0x43850
runtime.gentraceback(0xffff00200000?, 0x4000050500?, 0xfffff9bd8488?, 0x40000021a0, 0x0, 0x0, 0x7fffffff, 0xd4f030, 0xfffff9bd8480?, 0x0)
        runtime/traceback.go:270 +0x14bc fp=0xfffff9bd8420 sp=0xfffff9bd80b0 pc=0x67f1c
runtime.copystack(0x40000021a0, 0x200000)
        runtime/stack.go:934 +0x2fc fp=0xfffff9bd85e0 sp=0xfffff9bd8420 pc=0x5ce8c
runtime.newstack()
        runtime/stack.go:1114 +0x36c fp=0xfffff9bd8790 sp=0xfffff9bd85e0 pc=0x5d2dc
runtime.morestack()
        runtime/asm_arm64.s:316 +0x70 fp=0xfffff9bd8790 sp=0xfffff9bd8790 pc=0x72a40

goroutine 1 [copystack]:
runtime.call1048576(0x40006ff4a8, 0x1a650, 0xffffffffffffffff, 0x0, 0x0, 0x2101, 0x40002ea3e8)
        runtime/asm_arm64.s:494 +0xf8 fp=0x40006ff450 sp=0x40006ff450 pc=0x73eb8
github.com/equinix/terraform-provider-equinix/equinix.Provider()
        github.com/equinix/terraform-provider-equinix/equinix/provider.go:47 +0x4 fp=0x40006ff450 sp=0x40006ff450 pc=0x9bd0e4
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*GRPCProviderPlugin).GRPCServer(0x40006ff4d8, 0x923a40?, 0xb78e40)
        github.com/hashicorp/terraform-plugin-go@v0.19.0/tfprotov5/tf5server/plugin.go:48 +0x2c fp=0x40006ff4a0 sp=0x40006ff450 pc=0x9404ec
runtime: g 1: unexpected return pc for github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*GRPCProviderPlugin).GRPCServer called from 0x40002ea360
stack: frame={sp:0x40006ff4a0, fp:0x40006ff4f0} stack=[0x4000500000,0x4000700000)
0x00000040006ff3a0:  0x0000000000000000  0x0000000000000000 
0x00000040006ff3b0:  0x0000000000000000  0x0000000000000000 
0x00000040006ff3c0:  0x0000000000000000  0x0000000000000000 
0x00000040006ff3d0:  0x0000000000000000  0x0000000000000000 
0x00000040006ff3e0:  0x0000000000000000  0x0000000000000000 
0x00000040006ff3f0:  0x0000000000000000  0x0000000000000000 
0x00000040006ff400:  0x0000000000000000  0x0000000000000000 
0x00000040006ff410:  0x0000000000000000  0x0000000000000000 
0x00000040006ff420:  0x0000000000000000  0x0000000000000000 
0x00000040006ff430:  0x0000000000000000  0x0000000000000000 
0x00000040006ff440:  0x0000000000000000  0x0000000000000000 
0x00000040006ff450:  0x00000000009404ec <github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*GRPCProviderPlugin).GRPCServer+0x000000000000002c>  0x00000040006ff4a8 
0x00000040006ff460:  0x000000000001a650 <runtime.assertI2I2+0x0000000000000040>  0xffffffffffffffff 
0x00000040006ff470:  0x0000000000000000  0x0000004000002101 
0x00000040006ff480:  0x00000040002ea3e8  0x000000400031f4d8 
0x00000040006ff490:  0x0000000000923a60 <github.com/hashicorp/go-plugin.(*GRPCServer).Init+0x00000000000005b0>  0x00000040002e8390 
0x00000040006ff4a0: <0x00000040002ea360  0x00000040006ff4d8 
0x00000040006ff4b0:  0x0000000000923a40 <github.com/hashicorp/go-plugin.(*GRPCServer).Init+0x0000000000000590>  0x0000000000b78e40 
0x00000040006ff4c0:  0x0000000000ba0a00  0x000000400031f401 
0x00000040006ff4d0:  0x00000040002e83c0  0x000000400031f678 
0x00000040006ff4e0:  0x000000000092785c <github.com/hashicorp/go-plugin.Serve+0x00000000000009dc>  0x00000040002e83c0 
0x00000040006ff4f0: >0x0000000000e592c0  0x00000040002121e0 
0x00000040006ff500:  0x00000040002412c0  0x0000000000e576c0 
0x00000040006ff510:  0x00000040000b8ab0  0x000000400031f5d8 
0x00000040006ff520:  0x000000000001c4bc <runtime.mallocgc+0x000000000000058c>  0x0000000000000001 
0x00000040006ff530:  0x0000000000000000  0x0000000000000008 
0x00000040006ff540:  0x0000000080002005  0x0000000000000000 
0x00000040006ff550:  0x0000000000000000  0x00000040000b8ac8 
0x00000040006ff560:  0x0000004000398080  0x00000040002e9e60 
0x00000040006ff570:  0x00000040002e9c20  0x00000040001b2480 
0x00000040006ff580:  0x0000000000cc9486  0x0000000000b41600 
0x00000040006ff590:  0x00000040000b8ac0  0x000000400009f6e0 
0x00000040006ff5a0:  0x00000040002e9f20  0x0000000000000000 
0x00000040006ff5b0:  0x000000400009f680  0x000000400009f620 
0x00000040006ff5c0:  0x000000400009f5c0  0x00000040002e9c50 
0x00000040006ff5d0:  0x00000040002e9bf0  0x0000004000389f08 
0x00000040006ff5e0:  0x0000000000000000  0x00000040001b4a20 
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*GRPCProviderPlugin).GRPCServer(0x40002121e0, 0x40002412c0?, 0xe576c0)
        github.com/hashicorp/terraform-plugin-go@v0.19.0/tfprotov5/tf5server/plugin.go:48 +0x2c fp=0x40006ff4f0 sp=0x40006ff4a0 pc=0x9404ec

goroutine 2 [force gc (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
        runtime/proc.go:381 +0xe0 fp=0x400006efa0 sp=0x400006ef80 pc=0x462c0
runtime.goparkunlock(...)
        runtime/proc.go:387
runtime.forcegchelper()
        runtime/proc.go:305 +0xb0 fp=0x400006efd0 sp=0x400006efa0 pc=0x46110
runtime.goexit()
        runtime/asm_arm64.s:1172 +0x4 fp=0x400006efd0 sp=0x400006efd0 pc=0x74da4
created by runtime.init.6
        runtime/proc.go:293 +0x24

goroutine 3 [GC sweep wait]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
        runtime/proc.go:381 +0xe0 fp=0x400006f760 sp=0x400006f740 pc=0x462c0
runtime.goparkunlock(...)
        runtime/proc.go:387
runtime.bgsweep(0x0?)
        runtime/mgcsweep.go:278 +0x98 fp=0x400006f7b0 sp=0x400006f760 pc=0x32b98
runtime.gcenable.func1()
        runtime/mgc.go:178 +0x28 fp=0x400006f7d0 sp=0x400006f7b0 pc=0x27c58
runtime.goexit()
        runtime/asm_arm64.s:1172 +0x4 fp=0x400006f7d0 sp=0x400006f7d0 pc=0x74da4
created by runtime.gcenable
        runtime/mgc.go:178 +0x6c

goroutine 4 [GC scavenge wait]:
runtime.gopark(0x4000046070?, 0xe4e768?, 0x1?, 0x0?, 0x0?)
        runtime/proc.go:381 +0xe0 fp=0x400006ff50 sp=0x400006ff30 pc=0x462c0
runtime.goparkunlock(...)
        runtime/proc.go:387
runtime.(*scavengerState).park(0x15c56e0)
        runtime/mgcscavenge.go:400 +0x5c fp=0x400006ff80 sp=0x400006ff50 pc=0x30b2c
runtime.bgscavenge(0x0?)
        runtime/mgcscavenge.go:628 +0x44 fp=0x400006ffb0 sp=0x400006ff80 pc=0x31064
runtime.gcenable.func2()
        runtime/mgc.go:179 +0x28 fp=0x400006ffd0 sp=0x400006ffb0 pc=0x27bf8
runtime.goexit()

Error: The terraform-provider-equinix_v1.18.1 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

### Expected Behavior

no panic on ARM

### Actual Behavior

panic on ARM

### Steps to Reproduce

`terraform apply`

Note: 1.5.7 panics even sooner, during `terraform init`.

**Comment by displague** [comment]
This is still a problem:
```
Terraform v1.7.1
on linux_arm64
+ provider registry.terraform.io/equinix/equinix v1.26.0
```
