### ISSUE TITLE
panic during "make acctest" in flattenACLTemplateInboundRules

### ISSUE THREAD

**Issue by displague** [equinix/terraform-provider-equinix#75]
```
--- FAIL: TestAccNetworkDeviceLink (2.15s)
panic: runtime error: index out of range [3] with length 3

goroutine 3025 [running]:
github.com/equinix/terraform-provider-equinix/equinix.flattenACLTemplateInboundRules({0xc0018f6000, 0x3, 0x1bea958}, {0xc00163a500, 0x4, 0xc0002691a0})
	/Users/marques/src/terraform-provider-equinix/equinix/resource_network_acl_template.go:351 +0x593
github.com/equinix/terraform-provider-equinix/equinix.updateACLTemplateResource(0xc001724840, 0xc0008a59d1)
	/Users/marques/src/terraform-provider-equinix/equinix/resource_network_acl_template.go:309 +0x508
github.com/equinix/terraform-provider-equinix/equinix.resourceNetworkACLTemplateRead({0xc001803080, 0xc0008a59d1}, 0xc001803080, {0x1ac9d20, 0xc0023801e0})
	/Users/marques/src/terraform-provider-equinix/equinix/resource_network_acl_template.go:244 +0x22b
github.com/equinix/terraform-provider-equinix/equinix.resourceNetworkACLTemplateCreate({0x1e97a58, 0xc000fe9080}, 0xc001c77778, {0x1ac9d20, 0xc0023801e0})
	/Users/marques/src/terraform-provider-equinix/equinix/resource_network_acl_template.go:227 +0x152
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xc00022e8c0, {0x1e979e8, 0xc0014d9340}, 0x2, {0x1ac9d20, 0xc0023801e0})
	/Users/marques/.local/share/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.9.0/helper/schema/resource.go:341 +0x12e
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc00022e8c0, {0x1e979e8, 0xc0014d9340}, 0xc00063b450, 0xc001802f00, {0x1ac9d20, 0xc0023801e0})
	/Users/marques/.local/share/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.9.0/helper/schema/resource.go:467 +0x871
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc000713248, {0x1e979e8, 0xc0014d9340}, 0xc001c98410)
	/Users/marques/.local/share/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.9.0/helper/schema/grpc_provider.go:977 +0xd8a
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc0006edda0, {0x1e97a90, 0xc001a0d680}, 0xc000ad8700)
	/Users/marques/.local/share/go/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.4.0/tfprotov5/tf5server/server.go:332 +0x6c
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x1ba1960, 0xc0006edda0}, {0x1e97a90, 0xc001a0d680}, 0xc000fe8900, 0x0)
	/Users/marques/.local/share/go/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.4.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:380 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000623a40, {0x1eaa008, 0xc001a46180}, 0xc001e26600, 0xc00152ed20, 0x25ba860, 0x0)
	/Users/marques/.local/share/go/pkg/mod/google.golang.org/grpc@v1.36.0/server.go:1217 +0xc8f
google.golang.org/grpc.(*Server).handleStream(0xc000623a40, {0x1eaa008, 0xc001a46180}, 0xc001e26600, 0x0)
	/Users/marques/.local/share/go/pkg/mod/google.golang.org/grpc@v1.36.0/server.go:1540 +0xa2a
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	/Users/marques/.local/share/go/pkg/mod/google.golang.org/grpc@v1.36.0/server.go:878 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/Users/marques/.local/share/go/pkg/mod/google.golang.org/grpc@v1.36.0/server.go:876 +0x294
FAIL	github.com/equinix/terraform-provider-equinix/equinix	5.799s
FAIL
make: *** [testacc] Error 1
```

### Terraform Version

TF: 1.0.11
Equinix: fba542a

**Comment by ocobleseqx** [comment]
Current API version still accepts the deprecated attribute "subnets" but response returns an inbound rule for each single subnet:

**Request:**
```
inboundRules:
  - subnets: [ "1.1.1.1/1", "2.2.2.2/2"]
```

**Response:**
```
inboundRules:
  - subnets: ["1.1.1.1/1"]
    subnet: "1.1.1.1/1"
  - subnets: ["2.2.2.2/2"]
    subnet: "2.2.2.2/2"
```

It was assumed that the request slice and the response slice were the same length causing that panic error in below line

https://github.com/equinix/terraform-provider-equinix/blob/fba542a017c143dee0b7e8de3ab6d6843ef193ca/equinix/resource_network_acl_template.go#L351

This function was already removed in #79 and acceptance test working as expected

https://github.com/equinix/terraform-provider-equinix/pull/79/files#diff-31ba13d83d29830e62c7086c45cc605063a7785628ba390067ff74813a9531b5
